### ISSUE TITLE
White blank page when Cloudflare Access Bitbucket Plugin is enabled

### ISSUE THREAD

**Issue by mschantl05** [cloudflare/cloudflare-access-for-atlassian#43]
Affected System:
Bitbucket 6.6.2
Cloudflare Access Bitbucket Plugin 2.10.0

When we enable the plugin we get a blank white page with no error message after the Azure AD Login. 

Log: ERROR [https-jsse-nio-8443-exec-126]  o.a.c.c.C.[Tomcat].[localhost] Exception Processing ErrorPage[errorCode=401, location=/mvc/error401]

**Comment by felipebn** [comment]
Hi @mschantl05, thanks for reporting it.

I was able to reproduce it affects Bitbucket > 6.0 and will look into a fix soon.

**Comment by felipebn** [comment]
Hi @mschantl05, this is fixed on 2.11.0 release.

**Comment by mschantl05** [comment]
Hi @felipebn, thank you very much, it works now.
