### ISSUE TITLE
Logout doesn't work right

### ISSUE THREAD

**Issue by mschantl05** [cloudflare/cloudflare-access-for-atlassian#48]
We are experiencing an issue with the logout functionality of the CFA Plugin for Atlassian. Clicking the Logout Button does not actually log you out (there is a "logout success" message, and we believe that it does actually perform some kind of logout, but when you go back to the application, you are still logged in) and the only way to do so is by clearing cookies for the site (confirmed on JIRA and Bitbucket).

Jira: v8.5.1
Bitbucket: v6.8.0
Plugin:  2.11

**Comment by AustinCorridor** [comment]
Thanks for the feedback. The plugin uses the cookie that Access signs in the browser. When the user logs out of the Atlassian session, they do log out of that current session (and the message from Atlassian is displayed) but the token is likely still active and present in the browser. The user can then redirect back and login.

We'll take a look at making the Atlassian logout flow call the Access logout endpoint.

**Comment by felipebn** [comment]
This is fixed on version [v2.11.1](https://github.com/cloudflare/cloudflare-access-for-atlassian/releases/tag/v2.11.1) .
