### ISSUE TITLE
Allow Username attribute for authentication

### ISSUE THREAD

**Issue by reneneisser** [cloudflare/cloudflare-access-for-atlassian#49]
At the moment, the plugins use `UserTermKeys.EMAIL` for authentication.

Not all of our users have the email attribute set in a way that allows authentication via Cloudflare Access, so the ability for JIRA Administrators to switch the field used for authentication to username (`UserTermKeys.USERNAME`) would be really helpful.

**Comment by felipebn** [comment]
This is available on 2.12.0 release.
