### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by frusznyak** [cloudflare/cloudflare-access-for-atlassian#69]
Is this project abandoned?
(Looks like dependabot PRs are no longer merged and the latest release is almost 1 year old)

**Comment by TownLake** [comment]
Hi there - it's not abandoned, but we are a bit behind on merging those auto-updates in.

Beyond those dependency upgrades, are you noticing other issues or are there features you're looking to see us add?

**Comment by frusznyak** [comment]
Hi Samuel, perfect thanks a bunch for the fast feedback!
I'm not aware of any issues or missing features atm.
Just wanted to make sure that this plugin is still active (more or less) before incorporating it into one of our internal jira/confluence instances (a smaller on-prem setup with about 100-150 active users) since the users will have to be familiarised with CF Access.

Thanks again, i'll close this issue.
